[project]
name = "server"
version = "0.1.0"
description = "this project is kinda like vibe coder tool "
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.15.0",
    "pandas>=2.3.2",
    "pyarrow>=21.0.0",
]
